#!/bin/sh -x

###
# Script will install a small HTML5 project
# Running: ~/ . project [project-name] [type]
# by appending the . this project will jump into the directory path created at /project/dev
###

###
## types
#
# exp           - Basic fast deploy experiment mode, designed for css and minimal js tests
# browserify    - The Future - browserify for node in the frontend / common js modules
# express       - Creates a skeleton express app

# assign default type if none given
TYPE=${2:-exp}
LOCATION=.

mkdir $1
cd $1

cwd=$(pwd)

# import relevant script
case "$TYPE" in
  lambda)
    # set generator path
    cd LOCATION
    GENERATOR=generator--lambda
    ;;  
  es6)
    # set generator path
    cd LOCATION
    GENERATOR=generator--es6
    ;;  
  vue)
    # set generator path
    cd LOCATION
    GENERATOR=generator--browserify-vue
    ;;
  vue-spa)
    # set generator path
    cd LOCATION
    GENERATOR=generator--vue-spa
    ;;
  vue-spa)
    # set generator path
    cd LOCATION
    GENERATOR=generator--spa
    ;;
  static)
    # set generator path
    cd LOCATION
    GENERATOR=generator--static
    ;;
  microsite)
    # set generator path
    cd LOCATION
    GENERATOR=generator--microsite
    ;;
  express)
    # set generator path
    cd LOCATION
    GENERATOR=generator--express
    ;;
  electron)
    # set generator path
    cd LOCATION
    GENERATOR=generator--electron
    ;;
  *)  
    # set generator path
    cd LOCATION
    GENERATOR=generator--es6
    ;;
esac

# clone generator
git clone https://github.com/dev-boilerplates/$GENERATOR

# remove git from clone
cd $GENERATOR
rm -Rf .git
cd ..

# move clone to cwd then kill
cp -a $GENERATOR/. $cwd
#cp -R $GENERATOR $cwd
rm -Rf $GENERATOR

# replace CONSTANT with project name variable in the following files
sed "s/__PROJECTNAME/$1/" package.json > package
sed "s/__PROJECTNAME/$1/" readme.md > readme

# rename above files to their true extension
mv package package.json
mv readme readme.md 

# setup stylesheets (ignoring previous stylesheet templates from now on)
rm -Rf stylus
git clone https://github.com/dev-boilerplates/stylus
cd stylus
rm -Rf .git
cd ..

# build
git init
npm install

git add .
git commit -am 'Initialise project.'

echo "Ready! -- start up a live server using 'npm start'"

s . # open with sublime